export enum ErrorType {
  //key : code_message
  E201_ACCOUNT_ALREADY_EXISTS = 'Account already exists',
  E202_ACCOUNT_NOT_FOUND = 'Account not found',
  E205_ALREADY_VERIFIED_OTP = 'Already verified otp',
  E206_USER_NOT_HAVE_SECRET_OTP = 'No account having secret for otp',
  E207_ALREADY_VERIFIED_OTP = 'Already verified otp',
  E208_NO_OTP_TOKEN = 'No OTP token',
  E209_NOT_MATCHED_SIXDIGIT = 'Not matched code',
  E210_EXCEEDED_TIMEOUT_FOR_VERIFY = 'Exceed 30 min',
  E211_NO_SIXDIGIT_CODE = 'No Six-Digit Code',
  E212_WRONG_ACCOUNT_TYPE = 'Account type Error',
  E213_NO_TOKEN = 'No token',
  E214_INVALID_TOKEN = 'Invalid token',
  E215_NO_EMAIL_INTPU = 'No Email input',
  E216_NOT_EXISTS_VERIFY_CODE = 'Not exist verify code',
  E217_NOT_EXISTS_EMAIL = 'Not exist email',
  E218_ALREADY_DISABLED_OTP = 'Already disable otp',
  E219_NEW_PW_OR_ORIGIN_PW_EMPTY = 'New pw or origin pw are empty',
  E220_EXCEEDED_TIMEOUT = 'Exceed 10 min',
  E221_NEW_PW_AND_CONFIRM_PW_DIFF = 'New pw and confirm pw are different',
  E222_INCORRECT_PASSWORD = 'Incorrect password',
  E223_NEW_PW_AND_ORIGIN_PW_SAME = 'New pw and origin pw have to be different',
  E224_INVALID_USER = 'Invalid User',
  E225_NO_USER = 'There is no user with your input.',
  E226_NEED_KYC = 'You have to request KYC',
  E227_REGISTERD_KYC = 'Not registered KYC',
  E228_INVALID_OTP = 'Invalid OTP token',
  E229_NO_OTP_TOKEN = 'No OTP token',
  E230_EMAIL_INVALID = 'Invalid input email',
  E231_NO_EMAIL = 'no email input',
  E232_UNKNOWN_KYC_WEBHHOOK_TRIGGER = 'unknown webhook trigger',

  E301_CHANGER_DATA_PROVIDER_ERROR = 'changer data provider error',
  E302_INSUFFICIENT_BALANCE_FOR_FEE = 'InsufficientBalanceForFee',
  E303_WITHDRAW_DISABLED = 'WithdrawDisabled',
  E304_EXCEED_DEPTRATIO = 'exceed deptRatio',
  E305_INVALID_WITHDRAWSTATUS = 'invalid withdrawstatus',
  E306_NO_REQUESTED_WITHDRAW = 'no requested withdraw',
  E307_KYC_STATE_PENDING = 'KYC state pending',
  E308_KYC_STATE_REJECTED = 'KYC state rejected',
  E309_CURRENCY_NOT_FOUND = 'Currency not found',
  E310_NO_ID = 'no ID',
  E311_KOREAN_CANNOT_DEPOSIT = 'Sorry, Korean cannot deposit.',
  E312_NEED_CURRENCY_NAME = 'need currencyName',
  E313_ALREADY_EXIST_ADDRESS = 'already exist address',
  E314_THIS_CURRENCY_IS_NOT_DEPOSITENABLE = 'this currency is not depositEnable',
  E315_NOT_FOUND_CURRENCY = 'not found currency',
  E316_DEPSIT_DISABLED = 'DepositDisabled',
  E317_NO_WALLET_ADDRESS = 'no wallet address',
  E318_NO_CURRENCY = 'no currency',

  E351_PROHIBIT_KOREA_USER = 'Sorry, Korean Cannot trade',
  E352_NO_CURRENCY_DB = 'There is no currency in DB',
  E353_EMPTY_BALANCE = 'Empty balance. Please, Deposit to your asset.',

  E401_UNAUTHRIZED = 'Unauthorized Error',
  E402_INVALID_PARAMETER = 'Invalid Parameter',

  //Quote/ 거래
  E500_NO_QUOTE = 'There is no quote',
  E501_CREDIT_INVALID = 'You used all your credits. Please deposit more asset to get more credits.',
  E502_QUOTE_INVALID = 'Quotation got Invalid. Please check new quotation and try again',

  E600_ACCOUNT_NOT_EXIST = 'Account not exist',

  E1000_UNDEFINED_ERROR = 1000,

  E1001_INVALID_ACCESS = 'No access to this endpoint',
  E1002_NO_ROLES = 'No Roles to this endpoint',
  E1003_NEED_UPDATE_PW = 'Please update the password',
  E1004_NO_VERIFIED_OTP_USER = 'User should register the otp authentication',
  E1005_NO_WITHDRAW_TUPLE = 'There is no withdrawl tuple.',
}
